services:
  mysql:
    image: mysql:latest
    container_name: solidarity_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solidarityprueba
    ports:
      - '3306:3306'
    volumes:
      - mysql_data_solidarity_hub:/var/lib/mysql

volumes:
  mysql_data_solidarity_hub:
